ENVIRONMENT:
    MAX_EPISODE_STEPS: 300

DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/pick_datasets/pick_single_object.json.gz
    SCENES_DIR: "data/replica_cad/"
    EXPERT_TRAJ_DIR: "data/expert_trajs/"

TASK:
    TYPE: RearrangeSimplePickTask
    MAX_COLLISIONS: -1.0
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False
    DESIRED_RESTING_POSITION: [0.5, 0.0, 1.0]
    #DESIRED_RESTING_POSITION: [0.0, 0.5, 1.0]
    #DESIRED_RESTING_POSITION: [0.0, 1.0, 0.5]

    BASE_ANGLE_NOISE: 0.15 # In radians
    BASE_NOISE: 0.05
    CONSTRAINT_VIOLATION_ENDS_EPISODE: True
    FORCE_REGENERATE: False
    SHOULD_ENFORCE_TARGET_WITHIN_REACH: False

    # Measurements for composite tasks.
    REWARD_MEASUREMENT: "rearrangepick_reward"
    SUCCESS_MEASUREMENT: "rearrangepick_success"
    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False
    SENSORS: []

    ROBOT_FORCE:
        TYPE: "RobotForce"
        MIN_FORCE: 20.0
    EXCESSIVE_FORCE_SHOULD_END:
        TYPE: "ForceTerminate"
        MAX_ACCUM_FORCE: 5000.0
    ROBOT_COLLS:
        TYPE: "RobotCollisions"
    OBJECT_TO_GOAL_DISTANCE:
        TYPE: "ObjectToGoalDistance"
    END_EFFECTOR_TO_OBJECT_DISTANCE:
        TYPE: "EndEffectorToObjectDistance"
    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance_v2"
    DID_PICK_OBJECT:
        TYPE: "DidPickObjectMeasure"
    DID_PICK_CORRECT_OBJECT:
        TYPE: "DidPickCorrectObjectMeasure"
    PICK_REWARD:
        TYPE: "RearrangePickReward"
        DIST_REWARD: 20.0
        PICK_REWARD: 20.0
        DROP_PEN: 5.0
        WRONG_PICK_PEN: 5.0
        USE_DIFF: True
        DROP_OBJ_SHOULD_END: False
        WRONG_PICK_SHOULD_END: True
        # General Rearrange Reward config
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.001
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    PICK_SUCCESS:
        TYPE: "RearrangePickSuccess"
        SUCC_THRESH: 0.15
    MEASUREMENTS:
        - "OBJECT_TO_GOAL_DISTANCE"
        - "ROBOT_FORCE"
        - "EXCESSIVE_FORCE_SHOULD_END"
        - "ROBOT_COLLS"
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "END_EFFECTOR_TO_OBJECT_DISTANCE"
        - "DID_PICK_OBJECT"
        - "DID_PICK_CORRECT_OBJECT"
        - "PICK_SUCCESS"
        - "PICK_REWARD"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmEEAction" #"ArmRelPosAction"
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
            RENDER_EE_TARGET: False
    # ACTIONS:
    #     OK_ARM_ACTION:
    #         TYPE: "OkArmAction"
    #         ARM_CONTROLLER: "OkArmEEAction" 
    #         GRIP_CONTROLLER: "MagicGraspAction"
    #         ARM_JOINT_DIMENSIONALITY: 7  # why not parse from UDRF?
    #         GRASP_THRESH_DIST: 0.10 # 0.15
    #         DISABLE_GRIP: True # False
    #         DELTA_POS_LIMIT: 0.0125
    #         EE_CTRL_LIM: 0.015
    #         RENDER_EE_TARGET: False
    POSSIBLE_ACTIONS:
        - ARM_ACTION

RL:
    SUCCESS_REWARD: 100.0
    LIVING_PENALTY: 0.01


SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: False
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    ROBOT_JOINT_START_NOISE: 0.0
    FORCE_RECOMPUTE_NAVMESH: False
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: False
        RADIUS: 0.1
        SENSORS: ['THIRD_RGB_SENSOR']
        START_POSITION: [0, 0, 0]
        START_ROTATION: [0, 0, 0, 1]
    HEAD_RGB_SENSOR:
        WIDTH: 256 # 128
        HEIGHT: 256 # 128
    HEAD_DEPTH_SENSOR:
        WIDTH: 256 # 128
        HEIGHT: 256 # 128
        MIN_DEPTH: 0.0
        MAX_DEPTH: 10.0
        NORMALIZE_DEPTH: True
    THIRD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    ARM_DEPTH_SENSOR:
        HEIGHT: 256 # 128
        WIDTH: 256 # 128
        MAX_DEPTH: 10.0
        MIN_DEPTH: 0.0
        NORMALIZE_DEPTH: True
        HFOV: 120  # new arg
    ARM_RGB_SENSOR:
        HEIGHT: 256 # 128
        WIDTH: 256 # 128
        HFOV: 120  # new arg
    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 500.0 # 240.0 # 120.0
    AC_FREQ_RATIO: 2
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobotThirdPerson"
    IK_ARM_URDF: "./data/robots/hab_fetch/robots/fetch_onlyarm.urdf"
    FORWARD_STEP_SIZE: 0.25
    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0
    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
