ENVIRONMENT:
    MAX_EPISODE_STEPS: 400


DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/nat-rl/pickplace.json.gz
    SCENES_DIR: "data/replica_cad/"

RL:
    SUCCESS_REWARD: 100.0

TASK:
    TYPE: RearrangePickPlaceTask-v0
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False
    DESIRED_RESTING_POSITION: [0.0, 0.5, 1.0] # Relative to the robot COM. This rest position gives good view of the final table state

    SHOULD_ENFORCE_TARGET_WITHIN_REACH: False

    # In radians
    BASE_ANGLE_NOISE: 0.15
    BASE_NOISE: 0.05
    CONSTRAINT_VIOLATION_ENDS_EPISODE: True
    FORCE_REGENERATE: False

    # Measurements for composite tasks.
    REWARD_MEASUREMENT: "rearrangepickplace_reward"
    SUCCESS_MEASUREMENT: "rearrangepickplace_success"

    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False

    # These are "Sensor" types. Stuff that will populate the observation
    TARGET_START_SENSOR: # Relative position from EE to target object
        TYPE: "TargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    GOAL_SENSOR: # Relative positions from target object to its goal location
        TYPE: "GoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_TARGET_START_SENSOR:
        TYPE: "AbsTargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_GOAL_SENSOR:
        TYPE: "AbsGoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    JOINT_SENSOR: # Joint positions
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    END_EFFECTOR_SENSOR: # EE position
        TYPE: "EEPositionSensor"
    IS_HOLDING_SENSOR:
        TYPE: "IsHoldingSensor"
    RELATIVE_RESTING_POS_SENSOR: # Relative position from EE to its desired rest position
        TYPE: "RelativeRestingPositionSensor"
    SENSORS: ["TARGET_START_SENSOR", "GOAL_SENSOR", "JOINT_SENSOR", "IS_HOLDING_SENSOR", "END_EFFECTOR_SENSOR", "RELATIVE_RESTING_POS_SENSOR"]

    # These are all "Measure" types. This is stuff that will populate the info dict
    ROBOT_FORCE:
        TYPE: "RobotForce"
        MIN_FORCE: 20.0
    EXCESSIVE_FORCE_SHOULD_END:
        TYPE: "ForceTerminate"
        MAX_ACCUM_FORCE: 5000.0
    ROBOT_COLLS:
        TYPE: "RobotCollisions"
    OBJECT_TO_GOAL_DISTANCE:
        TYPE: "ObjectToGoalDistance"
    END_EFFECTOR_TO_OBJECT_DISTANCE:
        TYPE: "EndEffectorToObjectDistance"
    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance"
    DID_PICK_OBJECT:
        TYPE: "DidPickObjectMeasure"
    PICKPLACE_REWARD:
        TYPE: "RearrangePickPlaceReward"
        DIST_REWARD: 20.0
        PICK_REWARD: 20.0
        PLACE_REWARD: 30.0
        DROP_PEN: 5.0
        WRONG_PICK_PEN: 5.0
        USE_DIFF: True
        DROP_OBJ_SHOULD_END: False
        WRONG_PICK_SHOULD_END: True
        CONSTRAINT_VIOLATE_PEN: 10.0 # General Rearrange Reward config
        FORCE_PEN: 0.001
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
        SUCC_THRESH: 0.15
        MAX_COLLISIONS: 50
        MAX_COLLISIONS_PEN: 10.0
    PICKPLACE_SUCCESS:
        TYPE: "RearrangePickPlaceSuccess"
        SUCC_THRESH: 0.15
    MEASUREMENTS:
        - "OBJECT_TO_GOAL_DISTANCE" # Measures target object distance to its goal position
        #- "ROBOT_FORCE"
        #- "EXCESSIVE_FORCE_SHOULD_END"
        - "ROBOT_COLLS"
        - "END_EFFECTOR_TO_OBJECT_DISTANCE" # measures distance from EE to target object
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "DID_PICK_OBJECT"
        - "PICKPLACE_SUCCESS"
        - "PICKPLACE_REWARD"

    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
    POSSIBLE_ACTIONS:
        - ARM_ACTION


SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    DEBUG_RENDER: False # True
    DEBUG_RENDER_GOAL: False # True
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    ROBOT_JOINT_START_NOISE: 0.0
    FORCE_RECOMPUTE_NAVMESH: False
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: False
        RADIUS: 0.3
        SENSORS: ['THIRD_RGB_SENSOR', 'THIRD_DEPTH_SENSOR']
        START_POSITION: [0, 0, 0]
        START_ROTATION: [0, 0, 0, 1]
    HEAD_RGB_SENSOR:
        WIDTH: 256
        HEIGHT: 256
    HEAD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 1.0
        NORMALIZE_DEPTH: True
    THIRD_DEPTH_SENSOR:
        WIDTH: 256
        HEIGHT: 256
        MIN_DEPTH: 0.0
        MAX_DEPTH: 1.0
        NORMALIZE_DEPTH: True
        UUID: 'robot_third_depth'
    THIRD_RGB_SENSOR:
        HEIGHT: 256
        WIDTH: 256

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 4
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobotThirdPerson"
    FORWARD_STEP_SIZE: 0.25

    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0

    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
