---
dataset_path: "data/replica_cad/replicaCAD.scene_dataset_config.json"
additional_object_paths:
  - "data/objects/ycb/"
scene_sets:
  -
    name: "scene_train_split"
    included_substrings:
      - "v3_sc0_staging_00_bench"
    excluded_substrings: []
    comment: "v3_sc4_staging saved for evaluation"

object_sets:
  -
    name: "objects"
    included_substrings:
      - "013_apple"
      - "011_banana"
      - "018_plum"
      - "017_orange"
    excluded_substrings: []

receptacle_sets:
  -
    name: "table"
    included_object_substrings:
      - ""
    excluded_object_substrings: []
    included_receptacle_substrings:
      - "receptacle_aabb_Tbl1_Top1_frl_apartment_table_01"
    excluded_receptacle_substrings: []
  -
    name: "kitchen_counter_left"
    included_object_substrings:
      - ""
    excluded_object_substrings: []
    included_receptacle_substrings:
      - "counter_left_kitchen_counter"
    excluded_receptacle_substrings: []
  -
    name: "kitchen_counter_right"
    included_object_substrings:
      - ""
    excluded_object_substrings: []
    included_receptacle_substrings:
      - "counter_right_kitchen_counter"
    excluded_receptacle_substrings: []

scene_sampler:
  type: "subset"
  params:
    scene_sets: ["scene_train_split"]

object_samplers:
  -
    name: "table"
    type: "uniform"
    params:
      object_sets: ["objects"]
      receptacle_sets: ["table"]
      num_samples: [1, 1] 
      orientation_sampling: "up"
  # -
  #   name: "counter_left"
  #   type: "uniform"
  #   params:
  #     object_sets: ["objects"]
  #     receptacle_sets: ["kitchen_counter_left"]
  #     num_samples: [1, 1] 
  #     orientation_sampling: "up"
  # -
  #   name: "counter_right"
  #   type: "uniform"
  #   params:
  #     object_sets: ["objects"]
  #     receptacle_sets: ["kitchen_counter_right"]
  #     num_samples: [1, 1] 
  #     orientation_sampling: "up"

object_target_samplers:
  -
    name: "table_targets"
    type: "uniform"
    params:
      object_samplers: ["table"]
      receptacle_sets: ["table"]
      num_samples: [1, 1]
      orientation_sampling: "up"
  # -
  #   name: "counter_left_targets"
  #   type: "uniform"
  #   params:
  #     object_samplers: ["counter_left"]
  #     receptacle_sets: ["kitchen_counter_left"]
  #     num_samples: [1, 1]
  #     orientation_sampling: "up"
  # -
  #   name: "counter_right_targets"
  #   type: "uniform"
  #   params:
  #     object_samplers: ["counter_right"]
  #     receptacle_sets: ["kitchen_counter_right"]
  #     num_samples: [1, 1]
  #     orientation_sampling: "up"
