ENVIRONMENT:
    MAX_EPISODE_STEPS: 400

DATASET:
    TYPE: RearrangeDataset-v1
    SPLIT: train
    DATA_PATH: data/pickplace_datasets/spatial_reasoning/spatial_reasoning.json.gz
    SCENES_DIR: "data/replica_cad/"
    EXPERT_TRAJ_DIR: "data/expert_trajs/spatial_reasoning/"

TASK:
    TYPE: SpacialReasoningTask
    MAX_COLLISIONS: -1.0
    COUNT_OBJ_COLLISIONS: True
    COUNT_ROBOT_OBJ_COLLS: False
    #DESIRED_RESTING_POSITION: [0.9, 0.1, 1.1]
    DESIRED_RESTING_POSITION: [0.6, 0.0, 1.1]

    BASE_ANGLE_NOISE: 0.15 # In radians
    BASE_NOISE: 0.05
    CONSTRAINT_VIOLATION_ENDS_EPISODE: True
    FORCE_REGENERATE: True
    SHOULD_ENFORCE_TARGET_WITHIN_REACH: False

    # Measurements for composite tasks.
    REWARD_MEASUREMENT: "rearrangepickplace_reward"
    SUCCESS_MEASUREMENT: "rearrangepickplace_success"
    # If true, does not care about navigability or collisions with objects when spawning
    # robot
    EASY_INIT: False
    RELATIVE_TARGET_POSITION_SENSOR:
        TYPE: "RelativeTargetPositionSensor"
    GOAL_SENSOR:
        TYPE: "GoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_TARGET_START_SENSOR:
        TYPE: "AbsTargetStartSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    ABS_GOAL_SENSOR:
        TYPE: "AbsGoalSensor"
        GOAL_FORMAT: "CARTESIAN"
        DIMENSIONALITY: 3
    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    END_EFFECTOR_SENSOR:
        TYPE: "EEPositionSensor"
    IS_HOLDING_SENSOR:
        TYPE: "IsHoldingSensor"
    RELATIVE_RESTING_POS_SENSOR:
        TYPE: "RelativeRestingPositionSensor"
    RELATIVE_OBJECT_TO_GOAL_POS_SENSOR:
        TYPE: "RelativeObjectToGoalPositionSensor"
    SENSORS: []

    ROBOT_FORCE:
        TYPE: "RobotForce"
        MIN_FORCE: 20.0
    EXCESSIVE_FORCE_SHOULD_END:
        TYPE: "ForceTerminate"
        MAX_ACCUM_FORCE: 5000.0
    ROBOT_COLLS:
        TYPE: "RobotCollisions"
    OBJECT_TO_GOAL_DISTANCE:
        TYPE: "ObjectToGoalDistance"
    END_EFFECTOR_TO_OBJECT_DISTANCE:
        TYPE: "EndEffectorToObjectDistance"
    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance_v2"
    DID_PICK_OBJECT:
        TYPE: "DidPickObjectMeasure"
    DID_PICK_CORRECT_OBJECT:
        TYPE: "DidPickCorrectObjectMeasure"
    PLACED_OBJECT:
        TYPE: "PlacedObjectMeasure"
        SUCC_THRESH: 0.15
    PICKPLACE_REWARD:
        TYPE: "RearrangePickPlaceReward"
        DIST_REWARD: 20.0
        PICK_REWARD: 30.0
        PLACE_REWARD: 30.0
        DROP_PEN: 5.0
        WRONG_PICK_PEN: 10.0
        USE_DIFF: True
        DROP_OBJ_SHOULD_END: False
        WRONG_PICK_SHOULD_END: True
        LIVING_PENALTY: 0.01
        # General Rearrange Reward config
        CONSTRAINT_VIOLATE_PEN: 10.0
        FORCE_PEN: 0.001
        MAX_FORCE_PEN: 1.0
        FORCE_END_PEN: 10.0
    PICKPLACE_SUCCESS:
        TYPE: "RearrangePickPlaceSuccess"
        SUCC_THRESH: 0.1
    MEASUREMENTS:
        - "OBJECT_TO_GOAL_DISTANCE"
        - "ROBOT_FORCE"
        - "EXCESSIVE_FORCE_SHOULD_END"
        - "ROBOT_COLLS"
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "END_EFFECTOR_TO_OBJECT_DISTANCE"
        - "DID_PICK_OBJECT"
        - "DID_PICK_CORRECT_OBJECT"
        - "PLACED_OBJECT"
        - "PICKPLACE_SUCCESS"
        - "PICKPLACE_REWARD"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmEEAction" #"ArmRelPosAction"
            GRIP_CONTROLLER: "MagicGraspAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRASP_THRESH_DIST: 0.15
            DISABLE_GRIP: False
            DELTA_POS_LIMIT: 0.0125
            EE_CTRL_LIM: 0.015
            RENDER_EE_TARGET: False
        # BASE_VELOCITY:
        #     TYPE: "BaseVelAction"
        #     LIN_SPEED: 6.0
        #     ANG_SPEED: 6.0
        #     ALLOW_DYN_SLIDE: True
        #     END_ON_STOP: False
        #     ALLOW_BACK: True
        #     MIN_ABS_LIN_SPEED: 1.0
        #     MIN_ABS_ANG_SPEED: 1.0

    POSSIBLE_ACTIONS:
        - ARM_ACTION

RL:
    SUCCESS_REWARD: 100.0
    LIVING_PENALTY: 0.01


SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    DEBUG_RENDER: False
    DEBUG_RENDER_GOAL: False
    CONCUR_RENDER: True
    AUTO_SLEEP: True
    ROBOT_JOINT_START_NOISE: 0.0
    FORCE_RECOMPUTE_NAVMESH: False
    AGENT_0:
        HEIGHT: 1.5
        IS_SET_START_STATE: False
        RADIUS: 0.1
        SENSORS: ['THIRD_RGB_SENSOR']
        START_POSITION: [0, 0, 0]
        START_ROTATION: [0, 0, 0, 1]

    HEAD_RGB_SENSOR:
        WIDTH: 512
        HEIGHT: 512

    THIRD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 500.0 # 240.0 # 120.0
    AC_FREQ_RATIO: 2
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    ROBOT_TYPE: "FetchRobotThirdPerson"
    IK_ARM_URDF: "./data/robots/hab_fetch/robots/fetch_onlyarm.urdf"
    FORWARD_STEP_SIZE: 0.25
    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0
    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
